version: '3.8'

# Services
services:
  # Server service (Backend)
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./backend/.env  # Load environment variables from the backend .env file
    environment:
      - JWT_SECRET=backend_secret  # This can be overridden or added
    depends_on:
      - postgres

  # Client service (Frontend)
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - server

  # Database service (PostgreSQL)
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file: ./backend/.env  # Load environment variables from the backend .env file
    environment:
      - POSTGRES_USER=$POSTGRES_USER  # Use environment variable from .env
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data

# Volumes define
volumes: 
  pgdata:
